Ruby on Rails capstone project - Budget app
KingsleyIbe/budget-app pull request #5
Opened 2022-04-21 20:28 UTC by KingsleyIbe

##  Milestone changes

In this milestone, I implemented the project features according to the requirements.

2022-04-21 22:26 UTC, hiromataba requested changes
## Hi @KingsleyIbe 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 22:26 UTC, hiromataba commented on README.md
> +[Live project Demo](https://budget-m-app.herokuapp.com/)
- [ ] Good job :clap:  your work is amazing, however, you still have a deployment issue, Kindly check your deployment on chack the provided live link because this one :point_up:  is broken.

![image](https://user-images.githubusercontent.com/75126481/164561043-907d6c9e-2a06-4d3a-bef3-dc8f82e61fad.png)

2022-04-22 07:02 UTC, KingsleyIbe commented on README.md
> +[Live project Demo](https://budget-m-app.herokuapp.com/)
Hey @hiromataba 

Thanks for reviewing my work, I will kindly fix the broken link

2022-04-22 07:25 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 07:36 UTC, KingsleyIbe commented
Hey @elmar8287 

Thanks for reviewing and approving my project.

2022-04-22 07:36 UTC, merged